### ISSUE TITLE
Blurry text inside decorator using position: 'CenterCenter'

### ISSUE THREAD

**Issue by peteroid** [FormidableLabs/nuka-carousel#127]
When I try to center the decorator with the "CenterCenter", the text of the children seems to be blurry.

blurry result: ![screen shot 2016-07-13 at 6 39 02 pm](https://cloud.githubusercontent.com/assets/12689188/16852749/2e614cac-49be-11e6-97b0-a9dcf74bda3c.png)

Try different approaches from StackOverflow, such as adding `translateZ(0)` or `translate3d(...)`, but none of these work for me. However, this problem is fixed when I change the style in the class and let the position option unset for the decorator:

``` css
  .slider-decorator-1 {
    top: 50% !important;
    left: 50% !important;
    transform: translate(-50%,-50%) !important;
  }
```

fixed result: ![screen shot 2016-07-13 at 6 39 07 pm](https://cloud.githubusercontent.com/assets/12689188/16852742/284763c4-49be-11e6-887b-3b394de7c9ea.png)

I dunno why this can fix the blurry text. Any idea?

> One more thing: the blurry text doesn't always happen. It seems to me that the blurry text would happen on my Macbook Air but no the Macbook Pro.
