### ISSUE TITLE
width is set to 0 in server render

### ISSUE THREAD

**Issue by Merri** [FormidableLabs/nuka-carousel#37]
At the moment I have this in my CSS:

``` css
.slider-list[style*=";width:0;"] {
    width: auto !important;
}
```

This fixes issue where I get unnecessary extra visual flash when React renders nuka-carousel for the first time on client, because the image I have inside is set to 100%, but that equals to 0px on initial render and therefore I end up in zero width and height.

It would be better to default to `auto` when width is not known so that I can get rid of the above hack fix.
